# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: psicologomiguelcoria.github.io
title: Psicologo Miguel Coria
email: 
author: Psicologo Miguel Coria
description: > # "Como profesional en psicología clínica, brindo servicio de psicoterapia especializada en el modelo cognitivo conductual.También ofrezco mis servicios de psicoterapia a distancia por medio de video llamada.. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: ''
credits: 'Copyright &copy; 2025 Psicologo Miguel Coria. Todos los derechos reservados.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: telegram
    url: https://t.me/psicmiguelcoria
  - title: youtube
    url: https://www.youtube.com/@VeAlPsicologo
  - title: linkedin
    url: https://www.linkedin.com/in/psicmiguelcoriag
